name: Build and publish
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build dpkg
        run: dpkg-deb --build ./dpkg
      - name: Upload dpkg
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.BOARD }}-${{ matrix.MODEL }}
          path: ./dpkg.deb